import Link from "next/link";
import {
  Brain, FileText, Mic, Map, Code2, ChevronRight,
  Sparkles, Shield, Zap, Mail, ArrowRight, Star,
  CheckCircle, TrendingUp, Users, Award, Clock,
} from "lucide-react";

const features = [
  {
    icon: Mic,
    title: "AI Mock Interview",
    desc: "Practice with role-specific questions generated by AI. Choose 5, 10, or 15 questions and get instant scoring on every answer.",
    color: "from-violet-500 to-purple-500",
    badge: "Most Popular",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/30",
  },
  {
    icon: FileText,
    title: "Resume Analyzer",
    desc: "Upload your PDF resume and get ATS score, skill gap analysis, and actionable improvement suggestions powered by AI.",
    color: "from-blue-500 to-cyan-500",
    badge: null,
    badgeColor: "",
  },
  {
    icon: Mail,
    title: "Cover Letter Generator",
    desc: "Create tailored, professional cover letters for any job role in seconds. Just paste the job description and let AI do the rest.",
    color: "from-cyan-500 to-teal-500",
    badge: "New",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
  },
  {
    icon: Map,
    title: "Learning Roadmap",
    desc: "Get a personalized 3, 6, 9, or 12-month learning plan with weekly goals tailored to your target role and current level.",
    color: "from-orange-500 to-amber-500",
    badge: null,
    badgeColor: "",
  },
  {
    icon: Code2,
    title: "DSA Tracker",
    desc: "Track your data structures & algorithms practice. Log Easy, Medium, and Hard problems with visual progress charts.",
    color: "from-emerald-500 to-teal-500",
    badge: null,
    badgeColor: "",
  },
  {
    icon: Brain,
    title: "Analytics Dashboard",
    desc: "See your interview score trends, role breakdown, DSA progress, and recent activity in one beautiful dashboard.",
    color: "from-indigo-500 to-blue-500",
    badge: null,
    badgeColor: "",
  },
];

const steps = [
  {
    num: "01",
    title: "Upload Your Resume",
    desc: "Upload your PDF resume to get instant ATS analysis and improvement tips.",
    icon: FileText,
    color: "from-blue-500 to-cyan-500",
  },
  {
    num: "02",
    title: "Practice Mock Interviews",
    desc: "Choose your target role, select question count, and answer AI-generated questions.",
    icon: Mic,
    color: "from-violet-500 to-purple-500",
  },
  {
    num: "03",
    title: "Track & Improve",
    desc: "Review AI feedback, track score trends, and follow your personalized roadmap.",
    icon: TrendingUp,
    color: "from-emerald-500 to-teal-500",
  },
];

const stats = [
  { label: "AI-Powered Tools", value: "6+", icon: Sparkles },
  { label: "Question Bank", value: "∞", icon: Brain },
  { label: "Instant Feedback", value: "< 3s", icon: Zap },
  { label: "Free to Use", value: "100%", icon: Shield },
];

const testimonials = [
  {
    name: "Arjun Mehta",
    role: "SDE at Amazon",
    text: "The mock interview feature gave me real confidence. The AI feedback was surprisingly accurate and helped me fix my weak spots before the actual interview.",
    rating: 5,
  },
  {
    name: "Priya Sharma",
    role: "Data Scientist at Microsoft",
    text: "The 12-month roadmap feature is incredible. It gave me a structured plan I could actually follow. Landed my dream job in 6 months!",
    rating: 5,
  },
  {
    name: "Rahul Gupta",
    role: "Product Manager at Flipkart",
    text: "Cover letter generator saved me hours. It wrote better letters than I ever could, perfectly tailored to each job description.",
    rating: 5,
  },
];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background overflow-hidden">
      {/* Background Orbs */}
      <div className="fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute top-0 left-1/4 h-[600px] w-[600px] rounded-full bg-violet-600/15 blur-[130px]" />
        <div className="absolute bottom-0 right-1/4 h-[600px] w-[600px] rounded-full bg-indigo-600/15 blur-[130px]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[400px] w-[400px] rounded-full bg-purple-600/10 blur-[100px]" />
      </div>

      {/* ── Hero Section ── */}
      <section className="mx-auto max-w-7xl px-4 pt-24 pb-20 text-center sm:px-6 lg:px-8">
        {/* Badge */}
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1.5 text-sm font-medium text-violet-300 backdrop-blur-sm">
          <Sparkles className="h-3.5 w-3.5" />
          Powered by Groq · Llama 3.1 AI
        </div>

        {/* Headline */}
        <h1 className="mx-auto max-w-4xl text-5xl font-extrabold leading-tight tracking-tight text-white sm:text-6xl lg:text-7xl">
          Ace Every Interview with{" "}
          <span className="bg-gradient-to-r from-violet-400 via-purple-400 to-indigo-400 bg-clip-text text-transparent">
            AI Copilot
          </span>
        </h1>

        {/* Subheadline */}
        <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground sm:text-xl">
          Analyze your resume, practice mock interviews with AI, generate cover letters,
          and follow a personalized learning roadmap — all in one platform, completely free.
        </p>

        {/* CTA Buttons */}
        <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
          <Link
            href="/sign-up"
            className="group inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-8 py-4 text-base font-semibold text-white shadow-2xl shadow-violet-500/30 transition-all duration-300 hover:shadow-violet-500/50 hover:scale-105"
          >
            Get Started Free
            <ChevronRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
          </Link>
          <Link
            href="/sign-in"
            className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-8 py-4 text-base font-semibold text-white backdrop-blur-sm transition-all hover:bg-white/10 hover:border-white/20"
          >
            Sign In
          </Link>
        </div>

        {/* Trust Badges */}
        <div className="mt-10 flex flex-wrap items-center justify-center gap-6 text-sm text-muted-foreground">
          <span className="flex items-center gap-1.5"><Shield className="h-4 w-4 text-emerald-400" /> Free to use</span>
          <span className="flex items-center gap-1.5"><Zap className="h-4 w-4 text-yellow-400" /> Instant AI feedback</span>
          <span className="flex items-center gap-1.5"><Sparkles className="h-4 w-4 text-violet-400" /> No credit card required</span>
          <span className="flex items-center gap-1.5"><CheckCircle className="h-4 w-4 text-blue-400" /> No setup needed</span>
        </div>
      </section>

      {/* ── Stats Banner ── */}
      <section className="mx-auto max-w-5xl px-4 pb-20 sm:px-6 lg:px-8">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {stats.map((stat) => (
            <div key={stat.label}
              className="rounded-2xl border border-white/5 bg-white/3 p-6 text-center backdrop-blur-sm transition-all hover:border-white/10 hover:bg-white/5">
              <stat.icon className="mx-auto mb-3 h-6 w-6 text-violet-400" />
              <p className="text-3xl font-black text-white">{stat.value}</p>
              <p className="mt-1 text-xs text-muted-foreground">{stat.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── How It Works ── */}
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold text-white sm:text-4xl">
            How it{" "}
            <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
              works
            </span>
          </h2>
          <p className="mt-4 text-muted-foreground">Get interview-ready in 3 simple steps</p>
        </div>

        <div className="relative grid grid-cols-1 gap-8 sm:grid-cols-3">
          {/* Connector line */}
          <div className="absolute top-8 left-1/4 right-1/4 hidden h-px bg-gradient-to-r from-transparent via-violet-500/30 to-transparent sm:block" />

          {steps.map((step, i) => (
            <div key={step.num} className="relative flex flex-col items-center text-center">
              <div className={`mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${step.color} shadow-xl`}>
                <step.icon className="h-8 w-8 text-white" />
              </div>
              <div className="absolute -top-2 -right-2 sm:hidden flex h-7 w-7 items-center justify-center rounded-full bg-violet-600 text-xs font-black text-white">
                {i + 1}
              </div>
              <p className="mb-1 text-xs font-bold uppercase tracking-widest text-muted-foreground/60">{step.num}</p>
              <h3 className="mb-2 text-xl font-bold text-white">{step.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features Grid ── */}
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold text-white sm:text-4xl">
            Everything you need to{" "}
            <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
              land your dream job
            </span>
          </h2>
          <p className="mt-4 text-muted-foreground">
            A complete AI-powered toolkit for interview preparation
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="group relative overflow-hidden rounded-2xl border border-white/5 bg-white/3 p-6 backdrop-blur-sm transition-all duration-300 hover:border-white/10 hover:bg-white/5 hover:-translate-y-1"
            >
              {feature.badge && (
                <span className={`absolute top-4 right-4 rounded-full border px-2 py-0.5 text-xs font-semibold ${feature.badgeColor}`}>
                  {feature.badge}
                </span>
              )}
              <div className="absolute inset-0 -z-10 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <div className={`absolute inset-0 bg-gradient-to-br ${feature.color} opacity-5 rounded-2xl`} />
              </div>
              <div className={`mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${feature.color} shadow-lg transition-transform group-hover:scale-110`}>
                <feature.icon className="h-6 w-6 text-white" />
              </div>
              <h3 className="mb-2 text-lg font-semibold text-white">{feature.title}</h3>
              <p className="text-sm leading-relaxed text-muted-foreground">{feature.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Testimonials ── */}
      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8">
        <div className="mb-12 text-center">
          <h2 className="text-3xl font-bold text-white sm:text-4xl">
            Loved by{" "}
            <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
              developers
            </span>
          </h2>
          <p className="mt-4 text-muted-foreground">Real stories from real users</p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
          {testimonials.map((t) => (
            <div key={t.name}
              className="rounded-2xl border border-white/5 bg-white/3 p-6 backdrop-blur-sm transition-all hover:border-white/10 hover:-translate-y-1">
              <div className="mb-4 flex gap-1">
                {Array.from({ length: t.rating }).map((_, i) => (
                  <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                ))}
              </div>
              <p className="mb-6 text-sm leading-relaxed text-muted-foreground">&ldquo;{t.text}&rdquo;</p>
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-violet-600 to-indigo-600 text-sm font-bold text-white">
                  {t.name.charAt(0)}
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">{t.name}</p>
                  <p className="text-xs text-muted-foreground">{t.role}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Final CTA ── */}
      <section className="mx-auto max-w-4xl px-4 pb-24 sm:px-6 lg:px-8">
        <div className="relative overflow-hidden rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-600/20 to-indigo-600/20 p-12 text-center backdrop-blur-sm">
          <div className="absolute inset-0 -z-10">
            <div className="absolute top-0 left-1/2 -translate-x-1/2 h-64 w-64 rounded-full bg-violet-600/20 blur-3xl" />
          </div>
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-4 py-1.5 text-sm text-violet-300">
            <Users className="h-4 w-4" /> Join thousands of developers
          </div>
          <h2 className="mb-4 text-4xl font-extrabold text-white">
            Ready to ace your next interview?
          </h2>
          <p className="mb-8 text-lg text-muted-foreground">
            Start for free. No credit card. No setup. Just results.
          </p>
          <Link
            href="/sign-up"
            className="group inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-10 py-4 text-lg font-bold text-white shadow-2xl shadow-violet-500/40 transition-all hover:scale-105 hover:shadow-violet-500/60"
          >
            Get Started Free
            <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
          </Link>
          <p className="mt-4 text-xs text-muted-foreground/60">
            <Award className="inline h-3 w-3 mr-1" />
            Free forever · AI-powered · Built for developers
          </p>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-white/5 py-10">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
            <div className="flex items-center gap-2">
              <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-violet-600 to-indigo-600">
                <Brain className="h-4 w-4 text-white" />
              </div>
              <span className="font-bold text-white">AI <span className="text-violet-400">Copilot</span></span>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2026 AI Interview Copilot. Built with ❤️ for developers.
            </p>
            <div className="flex gap-6 text-sm text-muted-foreground">
              <Link href="/sign-in" className="hover:text-white transition-colors">Sign In</Link>
              <Link href="/sign-up" className="hover:text-white transition-colors">Sign Up</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
